### ISSUE TITLE
Change Configuration

### ISSUE THREAD

**Issue by MikeVezina** [Smart-Library/desk-controller#7]
I created this issue because this needs to be addressed. As we all know, we use addresses as opposed to pins to communicate with the sensor. We need to change the configuration file / loader to address this issue.

My proposed format is:

```
desks:
  - id: 1
    name: "Desk 1"
    sensor:
      type: 1
      i2c_bus: 1
      i2c_addr: 0xa

  - id : 2
    name: "Desk 2"
    sensor:
      type: 2
      pin: 5

# Define the different types of sensors
sensors:
  - type: 1
    name: "Omron D6T"
    interface: i2c

  - type: 2
    name: "Interrupt Driven Sensor"
    interface: pin
```
